# Generated by Django 2.2 on 2019-07-12 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginal', models.CharField(choices=[('XML', 'xml'), ('JSON', 'json'), ('CSV', 'csv')], max_length=4)),
                ('converted', models.CharField(choices=[('XML', 'xml'), ('JSON', 'json'), ('CSV', 'csv')], max_length=4)),
                ('filename', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
